package com.galactic.eightball;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.content.*;import java.io.*;import java.util.*;
public class MainActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);setContentView(new Game(this));}
 static class Ball{float x,y,vx,vy;int n; Ball(float X,float Y,int N){x=X;y=Y;n=N;}}
 class Game extends View{
  Paint p=new Paint(3);Bitmap felt;ArrayList<Ball> bs=new ArrayList<>();float L,T,R,B,rad;Ball cue;boolean drag=false;float sx,sy,px,py;Random rng=new Random(8);
  Game(Context c){super(c);setBackgroundColor(Color.rgb(1,3,10));try{for(String n:getAssets().list("extracted"))if(n.endsWith("_Felt.png"))felt=BitmapFactory.decodeStream(getAssets().open("extracted/"+n));}catch(Exception e){};setOnTouchListener((v,e)->touch(e));}
  protected void onSizeChanged(int w,int h,int a,int b){L=w*.055f;R=w*.945f;T=h*.09f;B=h*.91f;rad=h*.027f;reset();}
  void reset(){bs.clear();cue=new Ball(L+(R-L)*.23f,(T+B)/2,0);bs.add(cue);float bx=L+(R-L)*.70f,by=(T+B)/2,dx=rad*1.78f,dy=rad*2.05f;int n=1;for(int row=0;row<5;row++)for(int j=0;j<=row;j++)bs.add(new Ball(bx+row*dx,by+(j-row*.5f)*dy,n++));invalidate();}
  boolean touch(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==0){float dx=x-cue.x,dy=y-cue.y;if(dx*dx+dy*dy<rad*rad*9){drag=true;sx=x;sy=y;px=x;py=y;return true;}}if(e.getAction()==2&&drag){px=x;py=y;invalidate();return true;}if(e.getAction()==1&&drag){float dx=sx-x,dy=sy-y,d=(float)Math.sqrt(dx*dx+dy*dy);if(d>5){float k=Math.min(d,350)/18f;cue.vx=dx/d*k;cue.vy=dy/d*k;runPhysics();}drag=false;return true;}return true;}
  void runPhysics(){postOnAnimation(new Runnable(){public void run(){boolean go=false;for(Ball a:bs){a.x+=a.vx;a.y+=a.vy;a.vx*=.985f;a.vy*=.985f;if(Math.abs(a.vx)+Math.abs(a.vy)>.08)go=true;if(a.x-rad<L||a.x+rad>R){a.vx=-a.vx;a.x=Math.max(L+rad,Math.min(R-rad,a.x));}if(a.y-rad<T||a.y+rad>B){a.vy=-a.vy;a.y=Math.max(T+rad,Math.min(B-rad,a.y));}}for(int i=0;i<bs.size();i++)for(int j=i+1;j<bs.size();j++)hit(bs.get(i),bs.get(j));invalidate();if(go)postOnAnimation(this);}});}
  void hit(Ball a,Ball b){float dx=b.x-a.x,dy=b.y-a.y,d2=dx*dx+dy*dy,m=rad*2;if(d2>0&&d2<m*m){float d=(float)Math.sqrt(d2),nx=dx/d,ny=dy/d,ov=m-d;a.x-=nx*ov/2;b.x+=nx*ov/2;a.y-=ny*ov/2;b.y+=ny*ov/2;float rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){a.vx+=rel*nx;a.vy+=rel*ny;b.vx-=rel*nx;b.vy-=rel*ny;}}}
  protected void onDraw(Canvas c){super.onDraw(c);p.setColor(Color.rgb(15,18,24));c.drawRoundRect(L-rad*1.5f,T-rad*1.5f,R+rad*1.5f,B+rad*1.5f,rad,rad,p);if(felt!=null)c.drawBitmap(felt,null,new RectF(L,T,R,B),p);else{p.setColor(Color.rgb(8,40,55));c.drawRect(L,T,R,B,p);}for(float[] q:new float[][]{{L,T},{(L+R)/2,T},{R,T},{L,B},{(L+R)/2,B},{R,B}}){p.setColor(Color.BLACK);c.drawCircle(q[0],q[1],rad*1.25f,p);}for(Ball b:bs)ball(c,b);if(drag){p.setStrokeWidth(rad*.25f);p.setColor(Color.CYAN);c.drawLine(cue.x,cue.y,cue.x+(sx-px)*3,cue.y+(sy-py)*3,p);}p.setTextSize(rad*.75f);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);c.drawText("GALACTIC 8-BALL  •  DRAG FROM THE DEATH STAR TO SHOOT",(L+R)/2,T-rad*1.8f,p);}
  void ball(Canvas c,Ball b){if(b.n==0){p.setColor(Color.rgb(180,185,195));c.drawCircle(b.x,b.y,rad,p);p.setColor(Color.rgb(40,45,55));c.drawCircle(b.x+rad*.25f,b.y-rad*.18f,rad*.35f,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);c.drawCircle(b.x+rad*.25f,b.y-rad*.18f,rad*.22f,p);p.setStyle(Paint.Style.FILL);return;}float hue=(b.n*37)%360;p.setColor(Color.HSVToColor(new float[]{hue,.75f,.95f}));c.drawCircle(b.x,b.y,rad,p);p.setColor(Color.argb(150,255,255,255));c.drawCircle(b.x-rad*.25f,b.y-rad*.3f,rad*.23f,p);p.setColor(Color.WHITE);p.setTextSize(rad*.65f);p.setTextAlign(Paint.Align.CENTER);c.drawText(""+b.n,b.x,b.y+rad*.22f,p);}
 }
}