package com.galactic.eightball;
import android.app.*;import android.os.*;import android.opengl.*;import android.content.*;import java.io.*;import java.nio.*;import java.util.*;
public class MainActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);GLSurfaceView v=new GLSurfaceView(this);v.setEGLContextClientVersion(2);v.setRenderer(new R(this));setContentView(v);}
 static class M{FloatBuffer v;int n;M(float[]a){n=a.length/3;ByteBuffer b=ByteBuffer.allocateDirect(a.length*4).order(ByteOrder.nativeOrder());v=b.asFloatBuffer();v.put(a).position(0);}}
 static class R implements GLSurfaceView.Renderer{Context c;ArrayList<M> ms=new ArrayList<>();int pr;float ang=0;R(Context x){c=x;}
 public void onSurfaceCreated(GL10 g,EGLConfig e){GLES20.glClearColor(.01f,.01f,.025f,1);GLES20.glEnable(GLES20.GL_DEPTH_TEST);String vs="attribute vec3 p;uniform mat4 m;void main(){gl_Position=m*vec4(p,1.0);}";String fs="precision mediump float;void main(){gl_FragColor=vec4(.55,.58,.64,1.0);}";pr=GLES20.glCreateProgram();int a=sh(35633,vs),b=sh(35632,fs);GLES20.glAttachShader(pr,a);GLES20.glAttachShader(pr,b);GLES20.glLinkProgram(pr);load();}
 int sh(int t,String s){int x=GLES20.glCreateShader(t);GLES20.glShaderSource(x,s);GLES20.glCompileShader(x);return x;}
 void load(){try{for(String n:c.getAssets().list("extracted"))if(n.endsWith(".obj")){BufferedReader r=new BufferedReader(new InputStreamReader(c.getAssets().open("extracted/"+n)));ArrayList<float[]> vs=new ArrayList<>();ArrayList<Float> tri=new ArrayList<>();String l;while((l=r.readLine())!=null){if(l.startsWith("v ")){String[]q=l.trim().split("\\s+");vs.add(new float[]{Float.parseFloat(q[1]),Float.parseFloat(q[2]),Float.parseFloat(q[3])});}else if(l.startsWith("f ")){String[]q=l.trim().split("\\s+");for(int i=1;i<q.length-2;i++){int[]ix={idx(q[1]),idx(q[i+1]),idx(q[i+2])};for(int z:ix){float[]p=vs.get(z);tri.add(p[0]);tri.add(p[1]);tri.add(p[2]);}}}}float[]a=new float[tri.size()];for(int i=0;i<a.length;i++)a[i]=tri.get(i);if(a.length>0)ms.add(new M(a));}}catch(Exception e){}}
 int idx(String s){return Integer.parseInt(s.split("/")[0])-1;}
 public void onSurfaceChanged(GL10 g,int w,int h){GLES20.glViewport(0,0,w,h);}
 public void onDrawFrame(GL10 g){GLES20.glClear(16640);GLES20.glUseProgram(pr);float[]P=new float[16],V=new float[16],M=new float[16],PV=new float[16];Matrix.perspectiveM(P,0,45,2.0f,.1f,200);Matrix.setLookAtM(V,0,0,22,28,0,0,0,0,1,0);Matrix.multiplyMM(PV,0,P,0,V,0);Matrix.setIdentityM(M,0);Matrix.rotateM(M,0,ang,0,1,0);float[]F=new float[16];Matrix.multiplyMM(F,0,PV,0,M,0);int u=GLES20.glGetUniformLocation(pr,"m"),p=GLES20.glGetAttribLocation(pr,"p");GLES20.glUniformMatrix4fv(u,1,false,F,0);GLES20.glEnableVertexAttribArray(p);for(M m:ms){GLES20.glVertexAttribPointer(p,3,5126,false,0,m.v);GLES20.glDrawArrays(4,0,m.n);}GLES20.glDisableVertexAttribArray(p);ang+=.05f;}
 }}
}