package com.galactic.eightball;
import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import android.content.*;import java.io.*;import java.net.*;import java.security.*;
public class MainActivity extends Activity{
 static final String TABLE="https://steamusercontent-a.akamaihd.net/ugc/12707506843866704649/88B0FF640B639E479D43D04957146C9CA95D3224/";
 TestView v;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);v=new TestView(this);setContentView(v);new Thread(()->verify()).start();}
 void verify(){try{File f=new File(getFilesDir(),"galactic_table.unity3d");HttpURLConnection c=(HttpURLConnection)new URL(TABLE).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","Mozilla/5.0");try(InputStream in=c.getInputStream();FileOutputStream o=new FileOutputStream(f)){byte[]b=new byte[65536];int n;while((n=in.read(b))>0)o.write(b,0,n);}byte[]h=new byte[7];try(FileInputStream in=new FileInputStream(f)){in.read(h);}String sig=new String(h,"US-ASCII");String hash=sha(f);runOnUiThread(()->{v.status=sig.startsWith("Unity")?"REAL UNITY TABLE ASSET VERIFIED":"DOWNLOAD COMPLETE - SIGNATURE "+sig;v.detail=f.length()+" bytes  SHA-256 "+hash.substring(0,16)+"…";v.ok=sig.startsWith("Unity");v.invalidate();});}catch(Exception e){runOnUiThread(()->{v.status="ASSET LOAD FAILED";v.detail=e.getClass().getSimpleName()+": "+e.getMessage();v.invalidate();});}}
 String sha(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[]b=new byte[65536];int n;while((n=in.read(b))>0)d.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte x:d.digest())s.append(String.format("%02x",x));return s.toString();}
 class TestView extends View{Paint p=new Paint(3);String status="DOWNLOADING ORIGINAL GALACTIC TABLE ASSET…",detail="Using the recovered TTS/Unity AssetBundle reference";boolean ok=false;TestView(Context c){super(c);setBackgroundColor(Color.rgb(2,4,14));}
 protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.09f);p.setColor(ok?Color.rgb(110,235,170):Color.WHITE);c.drawText("GALACTIC 8-BALL",w/2,h*.28f,p);p.setTextSize(h*.055f);p.setColor(ok?Color.rgb(110,235,170):Color.rgb(120,190,255));c.drawText(status,w/2,h*.50f,p);p.setTypeface(Typeface.MONOSPACE);p.setTextSize(h*.03f);p.setColor(Color.LTGRAY);c.drawText(detail,w/2,h*.61f,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(h*.027f);p.setColor(Color.rgb(180,180,200));c.drawText("Asset-preservation port test • no recreated table graphics",w/2,h*.76f,p);}}
}