import struct,zlib,numpy as np,sys,os

class Node:
    __slots__=('name','props','children','start','end')
    def __init__(self,name,props,children,start,end):
        self.name=name;self.props=props;self.children=children;self.start=start;self.end=end

def read_prop(buf,pos):
    t=chr(buf[pos]);pos+=1
    if t=='Y': return struct.unpack_from('<h',buf,pos)[0],pos+2
    if t=='C': return buf[pos]!=0,pos+1
    if t=='I': return struct.unpack_from('<i',buf,pos)[0],pos+4
    if t=='F': return struct.unpack_from('<f',buf,pos)[0],pos+4
    if t=='D': return struct.unpack_from('<d',buf,pos)[0],pos+8
    if t=='L': return struct.unpack_from('<q',buf,pos)[0],pos+8
    if t in 'fdlib':
        n,enc,cl=struct.unpack_from('<III',buf,pos);pos+=12
        raw=buf[pos:pos+cl];pos+=cl
        if enc: raw=zlib.decompress(raw)
        dt={'f':'<f4','d':'<f8','l':'<i8','i':'<i4','b':'u1'}[t]
        return np.frombuffer(raw,dtype=dt,count=n).copy(),pos
    if t in 'SR':
        n=struct.unpack_from('<I',buf,pos)[0];pos+=4
        raw=buf[pos:pos+n];pos+=n
        return (raw.decode('utf-8','replace') if t=='S' else raw),pos
    raise ValueError('unknown property '+t)

def parse_node(buf,pos):
    start=pos
    if pos+13>len(buf): return None,pos
    endoff,np_,pl=struct.unpack_from('<III',buf,pos);pos+=12
    nl=buf[pos];pos+=1
    if endoff==0 and np_==0 and pl==0 and nl==0: return None,pos
    name=buf[pos:pos+nl].decode('utf-8','replace');pos+=nl
    props=[]
    for _ in range(np_):
        v,pos=read_prop(buf,pos);props.append(v)
    kids=[]
    while pos < endoff-13:
        c,npos=parse_node(buf,pos)
        if c is None:
            pos=npos;break
        kids.append(c);pos=npos
    return Node(name,props,kids,start,endoff),endoff

def parse_fbx(path):
    b=open(path,'rb').read()
    if not b.startswith(b'Kaydara FBX Binary'): raise ValueError('binary FBX required')
    ver=struct.unpack_from('<I',b,23)[0]
    if ver>=7500: raise ValueError('FBX >=7500 not supported by this small converter')
    pos=27;tops=[]
    while pos<len(b)-13:
        n,pos2=parse_node(b,pos)
        if n is None: break
        tops.append(n);pos=pos2
    objects=next(x for x in tops if x.name=='Objects')
    geo=next(x for x in objects.children if x.name=='Geometry' and len(x.props)>2 and x.props[2]=='Mesh')
    def ch(n,name): return next(x for x in n.children if x.name==name)
    V=ch(geo,'Vertices').props[0].reshape(-1,3).astype(np.float64)
    pvi=ch(geo,'PolygonVertexIndex').props[0].astype(np.int64)
    # Meshy exports triangulated models; validate so no accidental topology corruption.
    ends=np.nonzero(pvi<0)[0]
    if len(ends)==0 or np.any(np.diff(ends)!=3) or ends[0]!=2:
        raise ValueError('Expected triangulated Meshy FBX')
    F=np.where(pvi<0,-pvi-1,pvi).reshape(-1,3).astype(np.int64)
    leN=ch(geo,'LayerElementNormal')
    leU=ch(geo,'LayerElementUV')
    N=ch(leN,'Normals').props[0].reshape(-1,3).astype(np.float64)
    NI=ch(leN,'NormalsIndex').props[0].reshape(-1,3).astype(np.int64)
    UV=ch(leU,'UV').props[0].reshape(-1,2).astype(np.float64)
    UI=ch(leU,'UVIndex').props[0].reshape(-1,3).astype(np.int64)
    return V,F,N,NI,UV,UI

def cluster(V,F,res):
    mn=V.min(0);span=np.ptp(V,axis=0);span[span<1e-12]=1
    q=np.floor((V-mn)/span*res).astype(np.int32)
    q=np.clip(q,0,res-1)
    cells,inv=np.unique(q,axis=0,return_inverse=True)
    count=np.bincount(inv,minlength=len(cells)).astype(np.float64)
    C=np.empty((len(cells),3),np.float64)
    for k in range(3): C[:,k]=np.bincount(inv,weights=V[:,k],minlength=len(cells))/count
    MF=inv[F]
    good=(MF[:,0]!=MF[:,1])&(MF[:,1]!=MF[:,2])&(MF[:,0]!=MF[:,2])
    orig=np.nonzero(good)[0]
    MF=MF[good]
    # Remove duplicates generated by clustering but retain an original face for UV/normal data.
    sortedF=np.sort(MF,axis=1)
    _,first=np.unique(sortedF,axis=0,return_index=True)
    orig=orig[first]
    return C,inv,orig

def build(path,out,target_faces=15000):
    V,F,N,NI,UV,UI=parse_fbx(path)
    best=None
    for res in range(18,65):
        C,inv,orig=cluster(V,F,res)
        nf=len(orig)
        if nf<=target_faces: best=(res,C,inv,orig)
        else: break
    if best is None: raise RuntimeError('no cluster result')
    res,C,inv,orig=best
    nf=len(orig)
    # Explode retained triangles. This keeps per-corner UV seams and normals exact,
    # while clustered positions preserve a continuous low-poly silhouette.
    outv=np.empty((nf*3,8),np.float32)
    oi=np.empty((nf,3),np.uint32)
    for j,fi in enumerate(orig):
        for c in range(3):
            p=C[inv[F[fi,c]]]
            n=N[NI[fi,c]]
            ln=np.linalg.norm(n)
            if ln>1e-8:n=n/ln
            uv=UV[UI[fi,c]]
            k=j*3+c
            outv[k,:3]=p
            outv[k,3:6]=n
            outv[k,6]=uv[0]
            outv[k,7]=uv[1]
            oi[j,c]=k
    if len(outv)>65535: raise RuntimeError('16-bit vertex limit exceeded')
    raw=struct.pack('<II',len(outv),nf)+outv.astype('<f4').tobytes()+oi.astype('<u4').tobytes()
    comp=zlib.compress(raw,9)
    payload=b'SSM1'+struct.pack('<II',len(raw),len(comp))+comp
    open(out,'wb').write(payload)
    print(os.path.basename(path),'res',res,'orig faces',len(F),'clusters',len(C),'faces',nf,'verts',len(outv),'raw',len(raw),'ssm',len(payload),'bbox',V.min(0),V.max(0))

if __name__=='__main__':
    build(sys.argv[1],sys.argv[2],int(sys.argv[3]) if len(sys.argv)>3 else 15000)